# Generated by Django 4.0 on 2023-03-01 20:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('notes', '0003_quicknote'),
    ]

    operations = [
        migrations.AddField(
            model_name='quicknote',
            name='note',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='all_notes', to='notes.note'),
        ),
    ]
