# Generated by Django 4.0 on 2023-03-01 20:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('notes', '0004_quicknote_note'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='quicknote',
            name='note',
        ),
    ]
