# Generated by Django 4.0 on 2023-03-01 21:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('notes', '0005_remove_quicknote_note'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='quicknote',
            name='description',
        ),
        migrations.RemoveField(
            model_name='quicknote',
            name='title',
        ),
    ]
