# Generated by Django 4.0 on 2023-03-01 21:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notes', '0006_remove_quicknote_description_remove_quicknote_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='quicknote',
            name='description',
            field=models.TextField(blank=True, max_length=1255, null=True),
        ),
        migrations.AddField(
            model_name='quicknote',
            name='title',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
