# Generated by Django 4.0 on 2023-04-01 22:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('notes', '0009_quicknote_description_quicknote_title'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Note',
        ),
    ]
