# Generated by Django 4.0 on 2023-03-02 10:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notes', '0012_alter_quicknote_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quicknote',
            name='description',
            field=models.TextField(blank=True, max_length=100000, null=True),
        ),
    ]
