# Generated by Django 4.0 on 2023-03-03 12:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notes', '0013_alter_quicknote_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quicknote',
            name='description',
            field=models.TextField(max_length=100000, null=True),
        ),
        migrations.AlterField(
            model_name='quicknote',
            name='title',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
