# Generated by Django 4.0 on 2023-03-03 12:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('folders', '0002_note'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Note',
            new_name='FolderNote',
        ),
    ]
