# Generated by Django 4.0 on 2023-03-03 12:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('folders', '0004_rename_newfolder_foldername'),
    ]

    operations = [
        migrations.AddField(
            model_name='foldernote',
            name='name',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='folder', to='folders.foldername'),
        ),
        migrations.AlterField(
            model_name='foldername',
            name='title',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='foldernote',
            name='description',
            field=models.TextField(max_length=100000, null=True),
        ),
        migrations.AlterField(
            model_name='foldernote',
            name='title',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
