# Generated by Django 4.0 on 2023-03-03 13:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('folders', '0005_foldernote_name_alter_foldername_title_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='foldernote',
            name='name',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='folders.foldername'),
        ),
    ]
