# Generated by Django 4.0 on 2023-03-03 13:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('folders', '0008_rename_foldernote_note'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='foldername',
            name='number_of_notes',
        ),
    ]
