# Generated by Django 4.0 on 2023-03-15 00:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0009_profile_phone_number'),
        ('folders', '0012_remove_note_account_owner'),
    ]

    operations = [
        migrations.AddField(
            model_name='note',
            name='account_owner',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='user.profile'),
        ),
    ]
