# Generated by Django 4.0 on 2023-03-14 10:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0007_remove_profile_password'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='phone_number',
        ),
    ]
